version: "3"
services: 
    crysral-server:
        build: .
        ports: 
            - "5000:5000"
        volumes: 
            - ./:/app
            - /app/node_modules
        env_file: 
            - ./.env