version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "5000:80"
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    crysral-server:
        build: .
        # ports: 
        #     - "5000:5000"
        # volumes: 
        #     - ./:/app
        #     - /app/node_modules
        env_file: 
            - ./.env
        depends_on: 
            - mongo

    mongo: 
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=alexander
            - MONGO_INITDB_ROOT_PASSWORD=989991
        volumes: 
            - mongo-db:/data/db

volumes: 
    mongo-db: