version: "3"
services: 
    nginx:
        ports: 
            - "5000:80"
    crystal-server:
        build: 
            context: .
            args: 
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONG0_USER=${MONG0_USER}
            - MONGO_PASSWORD=${MONGO_PASSWORD}
            
        command: npm run dev
    mongo: 
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        volumes: 
            - mongo-db:/data/db