version: "3"
services:
    nginx:
        ports: 
            - "80:80" 
    crystal-server:
        build: 
            context: .
            args: 
                NODE_ENV: production
        environment: 
            - NODE_ENV=production
            - MONG0_USER=${MONG0_USER}
            - MONGO_PASSWORD=989991
        command: node server.js